(* Exhaustive verification of the bf16 converters, CPU-only (gh-ocannl-1069).

   [single_to_bfloat16] is what the host stubs run on every backend when a bf16 node is set from the
   host, and what every cc kernel storing a bf16 node runs, through the vector bridge
   [OCANNL_VEC_NARROW_BFLOAT16] when the store is vectorized. Its round-to-nearest-even bit-add used
   to carry 131072 NaN inputs out of the NaN class -- 0x7F800001 truncated to +inf, 0xFFFFFFFF
   wrapped to +0 -- a silent wrong value no curated corpus had caught, so the check is every input.

   - [single_to_bfloat16] over all 2^32 f32 bit patterns against a rounding ORACLE -- the format's
   decode table plus the rule that a code owns the interval between the midpoints to its neighbours,
   ties to the even code, infinity taking part as the code after 0x7F7F -- with every NaN held to
   its quieted, truncated image; where the compiler has [__bf16], against the native cast too. - The
   vector bridge on the same inputs, bit for bit against the scalar converter. - The pre-gh-1069
   arithmetic as the negative control: exactly 131072 NaN escapes, and agreement with the fixed
   converter on every non-NaN input. - [bfloat16_to_single] over all 65536 codes against the
   format's exact values, and the widen-and-narrow round trip.

   The sweep is in bf16_codec_exhaustive_stubs.c, which compiles the definition table's own text
   (bf16_codec.h, generated by gen_codec_header.exe). Under [@slow] because it takes seconds rather
   than milliseconds; [@check] still compiles it. *)

open Base

type sweep_buf =
  (int64, Stdlib.Bigarray.int64_elt, Stdlib.Bigarray.c_layout) Stdlib.Bigarray.Array1.t

external sweep_init : unit -> unit = "ocannl_bf16_sweep_init"
external sweep_narrow : int64 -> int64 -> sweep_buf -> unit = "ocannl_bf16_sweep_narrow"
external has_native : unit -> bool = "ocannl_bf16_has_native"
external has_convertvector : unit -> bool = "ocannl_bf16_has_convertvector"
external widen_bits : int -> int64 = "ocannl_bf16_widen_bits"
external widen : int -> float = "ocannl_bf16_widen"
external narrow_bits : int64 -> int = "ocannl_bf16_narrow_bits"
external reference_decode : int -> float = "ocannl_bf16_reference_decode"

(* Mirrors the OUT_* offsets in bf16_codec_exhaustive_stubs.c. *)
let out_native = 0
let out_vector = 1
let out_rounding = 2
let out_sign = 3
let out_inf = 4
let out_nan_escape = 5
let out_nan_code = 6
let out_control_escape = 7
let out_control_finite = 8
let out_native_payload = 9
let out_reported = 10
let out_records = 11
let max_records = 8
let out_reached = out_records + (3 * max_records)
let reached_words = 1024
let out_len = out_reached + reached_words
let two_pow_32 = 0x1_0000_0000
let inf_code = 0x7F80
let quiet_bit = 0x0040

(* The NaN inputs the pre-gh-1069 bit-add carries out of the NaN class, counted off the format:
   0x7F800001..0x7F808000 truncate to infinity (the rounding add does not reach bit 16), and
   0x7FFF8000..0x7FFFFFFF carry into the sign bit -- 32768 each, times two signs. *)
let prefix_escapes = 2 * (0x8000 + 0x8000)

let fresh_buf () : sweep_buf =
  let b = Stdlib.Bigarray.Array1.create Stdlib.Bigarray.int64 Stdlib.Bigarray.c_layout out_len in
  Stdlib.Bigarray.Array1.fill b 0L;
  b

(* One contiguous range per domain, capped at 8 as in half_codec_exhaustive. *)
let domains = Int.min 8 (Domain.recommended_domain_count ())

let run sweep total =
  let chunk = (total + domains - 1) / domains in
  let bufs = Array.init domains ~f:(fun _ -> fresh_buf ()) in
  let spawned =
    Array.init domains ~f:(fun i ->
        let base = Int.min total (i * chunk) in
        let count = Int.max 0 (Int.min chunk (total - base)) in
        Domain.spawn (fun () -> sweep (Int64.of_int base) (Int64.of_int count) bufs.(i)))
  in
  Array.iter spawned ~f:Domain.join;
  bufs

let sum bufs i = Array.fold bufs ~init:0 ~f:(fun acc b -> acc + Int64.to_int_exn b.{i})

let reached bufs =
  Array.init reached_words ~f:(fun w ->
      Array.fold bufs ~init:0L ~f:(fun acc b -> Int64.bit_or acc b.{out_reached + w}))

(* The offender records, in chunk order, so a failing run names the same inputs every time. *)
let records bufs =
  Array.concat_map bufs ~f:(fun b ->
      Array.init
        (Int64.to_int_exn b.{out_reported})
        ~f:(fun k ->
          let base = out_records + (3 * k) in
          (b.{base}, Int64.to_int_exn b.{base + 1}, Int64.to_int_exn b.{base + 2})))

let reason_name = function
  | 1 -> "the native __bf16 cast narrows it differently"
  | 2 -> "the vector bridge narrows it differently"
  | 3 -> "not the nearest code (ties to even)"
  | 4 -> "sign not carried over"
  | 5 -> "an infinity narrowed to a code other than 0x7F80"
  | 6 -> "a NaN narrowed to a non-NaN code"
  | 7 -> "a NaN narrowed to a NaN other than its quieted, truncated image"
  | r -> Printf.sprintf "unknown reason %d" r

(* Offenders go to stderr with their exact bit patterns: what a failing run needs and what a passing
   golden must not carry. A native or vector disagreement packs both codes ([other] << 16 |
   [scalar]). *)
let report_records rs =
  Array.iter rs ~f:(fun (bits, code, reason) ->
      if reason = 1 || reason = 2 then
        Stdio.eprintf "narrowing: input 0x%08Lx -> scalar 0x%04x, %s 0x%04x (%s)\n" bits
          (code land 0xFFFF)
          (if reason = 1 then "native" else "vector")
          (code lsr 16) (reason_name reason)
      else Stdio.eprintf "narrowing: input 0x%08Lx -> 0x%04x (%s)\n" bits code (reason_name reason))

let report_counts bufs =
  List.iter
    [
      ("native disagreements", out_native);
      ("native NaN payload differences (tolerated)", out_native_payload);
      ("vector-bridge disagreements", out_vector);
      ("misroundings", out_rounding);
      ("sign losses", out_sign);
      ("infinities on the wrong code", out_inf);
      ("NaNs narrowed to a non-NaN code", out_nan_escape);
      ("NaNs narrowed to the wrong NaN code", out_nan_code);
      ("NaN escapes under the pre-gh-1069 arithmetic (the negative control)", out_control_escape);
      ("non-NaN inputs where the pre-gh-1069 arithmetic differs", out_control_finite);
    ]
    ~f:(fun (what, i) ->
      let n = sum bufs i in
      if n > 0 then Stdio.eprintf "narrowing: %d %s (not part of the golden)\n" n what)

let same a b = Int64.equal (Int64.bits_of_float a) (Int64.bits_of_float b)
let codes = List.range 0 0x10000
let is_nan_code c = c land 0x7FFF > inf_code

let () =
  sweep_init ();
  let native = has_native () in
  let on = "a compiler without __bf16" in
  Stdio.eprintf "native __bf16 cross-check: %b; vector bridge arm: %s (not part of the golden)\n"
    native
    (if has_convertvector () then "__builtin_convertvector" else "per-lane scalar fallback");
  let started = Unix.gettimeofday () in
  let narrow = run sweep_narrow two_pow_32 in
  Stdio.eprintf "narrowing sweep: %.1fs; %d domains (not part of the golden)\n"
    (Unix.gettimeofday () -. started)
    domains;
  report_counts narrow;
  report_records (records narrow);
  Stdio.printf "bf16 converters, exhaustive sweep\n";
  Stdio.printf "  f32 bit patterns narrowed: %d\n" two_pow_32;
  Stdio.printf "  bf16 codes widened: %d\n" (List.length codes);

  Verdict.p
    "OCANNL_VEC_NARROW_BFLOAT16 narrows every f32 input to the code single_to_bfloat16 gives it, \
     bit for bit"
    (sum narrow out_vector = 0);
  Verdict.p
    "single_to_bfloat16 rounds every finite f32 input to the nearest bf16 code, ties to even, \
     overflowing to infinity from 0x7F7F8000 up"
    (sum narrow out_rounding = 0);
  Verdict.p
    "single_to_bfloat16 carries the sign of every f32 input over, zeros, infinities and NaNs \
     included"
    (sum narrow out_sign = 0);
  Verdict.p "every infinite f32 input narrows to the infinity 0x7F80 of its sign"
    (sum narrow out_inf = 0);
  Verdict.p "no NaN f32 input narrows to a non-NaN code" (sum narrow out_nan_escape = 0);
  Verdict.p
    "every NaN f32 input narrows to its quieted, truncated image (bits >> 16) | 0x0040, keeping \
     its sign and the top of its payload"
    (sum narrow out_nan_code = 0);
  Verdict.gated ~aggregation:`Environment ~when_:native ~on
    "single_to_bfloat16 agrees with the native __bf16 cast on every f32 input, NaNs up to payload"
    (sum narrow out_native = 0);

  (* The negative control. Without it, "no NaN escapes" would not show that the sweep can see one:
     the pre-gh-1069 arithmetic, swept over the same inputs through the same classification, must
     escape on exactly the inputs counted off the format above -- and nowhere else differ from the
     fixed converter, which is the fix's claim that only NaN inputs change. *)
  Verdict.pf "the pre-gh-1069 bit-add carries exactly %d NaN inputs out of the NaN class"
    prefix_escapes
    (sum narrow out_control_escape = prefix_escapes);
  Verdict.p "the pre-gh-1069 bit-add agrees with single_to_bfloat16 on every non-NaN f32 input"
    (sum narrow out_control_finite = 0);

  (* Non-vacuity: "no misrounding" read together with "and every code is reachable" -- a converter
     that flushed a range, or quieted NaNs to one canonical code, would lose codes here. A signaling
     NaN code is never produced: every NaN narrows with the quiet bit set. *)
  let reachable = reached narrow in
  let is_reached c =
    not (Int64.equal 0L (Int64.bit_and reachable.(c / 64) (Int64.shift_left 1L (c % 64))))
  in
  let expected_reachable c = c land 0x7FFF <= inf_code || c land 0x7FFF >= 0x7F80 lor quiet_bit in
  Stdio.printf "  distinct bf16 codes produced by narrowing: %d\n" (List.count codes ~f:is_reached);
  Verdict.p_all
    "narrowing f32 reaches every finite, infinite and quiet-NaN bf16 code, and no signaling-NaN \
     code"
    codes ~min:0x10000 ~f:(fun c -> Bool.equal (is_reached c) (expected_reachable c));

  (* Widening, all 65536 codes. The reference decode is the format read off its fields, computed in
     the stub next to the oracle -- so its monotonicity is also what licenses the oracle's use of
     midpoints. A NaN code is compared as bits: widening is exact, so it keeps sign and payload, and
     reading it through an OCaml float would quiet a signaling one on the way. *)
  let widened = Array.of_list (List.map codes ~f:widen) in
  let decode_ok c =
    let m = c land 0x7FFF in
    let signed v = if c land 0x8000 <> 0 then Float.neg v else v in
    if m < inf_code then same widened.(c) (signed (reference_decode m))
    else if m = inf_code then Float.equal widened.(c) (signed Float.infinity)
    else Int64.equal (widen_bits c) (Int64.of_int (c lsl 16))
  in
  Verdict.p_all
    "bfloat16_to_single widens all 65536 codes to their exact bf16 values, signed zero included, \
     and every NaN code to the f32 NaN with its sign and payload"
    codes ~min:0x10000 ~f:decode_ok;
  Verdict.p_all
    "the format's decode is strictly increasing over the 32640 non-negative finite codes"
    (List.range 0 (inf_code - 1))
    ~min:(inf_code - 1)
    ~f:(fun c -> Float.( < ) (reference_decode c) (reference_decode (c + 1)));
  Verdict.p_all "every non-NaN code survives a widen-and-narrow round trip" codes ~min:0x10000
    ~f:(fun c -> is_nan_code c || narrow_bits (widen_bits c) = c);
  Verdict.p_all
    "every NaN code widens and narrows back to itself with the quiet bit set, so every quiet NaN \
     code survives the round trip"
    codes ~min:0x10000 ~f:(fun c ->
      (not (is_nan_code c)) || narrow_bits (widen_bits c) = c lor quiet_bit);

  (* The C entry points' argument guards, exercised: a guard that has never fired is a claim about
     nothing. *)
  let refuses f =
    try
      f ();
      false
    with Invalid_argument _ -> true
  in
  let one_word : sweep_buf =
    Stdlib.Bigarray.Array1.create Stdlib.Bigarray.int64 Stdlib.Bigarray.c_layout 1
  in
  Verdict.p "the reference decode refuses a code that is not a finite bf16 magnitude"
    (refuses (fun () -> ignore (reference_decode inf_code : float))
    && refuses (fun () -> ignore (reference_decode (-1) : float)));
  Verdict.p "the widening entry points refuse a code outside 16 bits"
    (refuses (fun () -> ignore (widen 0x10000 : float))
    && refuses (fun () -> ignore (widen_bits (-1) : int64)));
  Verdict.p "the narrowing entry point refuses a pattern outside 32 bits"
    (refuses (fun () -> ignore (narrow_bits 0x1_0000_0000L : int))
    && refuses (fun () -> ignore (narrow_bits (-1L) : int)));
  Verdict.p "the sweep refuses a counters buffer too short to hold its results"
    (refuses (fun () -> sweep_narrow 0L 1L one_word));
  Verdict.p "the sweep refuses a negative base or count, or a range past 2^32"
    (refuses (fun () -> sweep_narrow (-1L) 1L (fresh_buf ()))
    && refuses (fun () -> sweep_narrow 0L (-1L) (fresh_buf ()))
    && refuses (fun () -> sweep_narrow 0xFFFF_FFFFL 2L (fresh_buf ())));

  (* The format's landmarks, as hex floats so the golden is platform-independent. *)
  Stdio.printf "  smallest subnormal (0x0001): %s\n" (Test_utils.hex_float widened.(0x0001));
  Stdio.printf "  largest subnormal (0x007F): %s\n" (Test_utils.hex_float widened.(0x007F));
  Stdio.printf "  smallest normal (0x0080): %s\n" (Test_utils.hex_float widened.(0x0080));
  Stdio.printf "  one (0x3F80): %s\n" (Test_utils.hex_float widened.(0x3F80));
  Stdio.printf "  largest finite (0x7F7F): %s\n" (Test_utils.hex_float widened.(0x7F7F));
  Stdio.printf "  negative zero (0x8000): %s\n" (Test_utils.hex_float widened.(0x8000))
