(* gh-ocannl-806: a top-level helper in a module without an [.mli] is an exported value, even when
   its author meant it to be private. Two incidental hand sweeps found many such exports and still
   undercounted one family twofold. This repository scan makes the census mechanical for direct
   [*.ml] modules in [arrayjit/lib/], [tensor/] and (gh-ocannl-1009) [lib/], the user-facing half.

   The matching policy lives in [test/support/dead_export_scan.ml] and its synthetic negative
   controls. In particular, qualified paths through aliases count, and a bare identifier inside the
   lexical scope of [open M] counts conservatively. The latter can mistake a shadowing local for
   [M]'s value; that false-positive direction is deliberate for this first cut. An [include M] uses
   nothing (gh-ocannl-1085): it makes the including module a further receiver, so [Utils.v] counts
   for [Datatypes.v] -- but a value the include re-exports and nobody spells is dead, as
   [Datatypes.mutable_list] was for years behind [Utils]. Source-declared [let] values starting with
   [_] are deliberately unused by OCaml convention and excluded by policy. Values generated by
   [of_sexp], [sexp], [compare], and [equal] derivings are exports too; the matching expression
   extensions count as references to the same generated names. The [sexp_of] converters, derived or
   hand-written, are excluded by policy (the support module's header says why): they are the
   debugging and observability entry point, and [ppx_minidebug]'s typed log annotations consume them
   invisibly to a source-level census. Other PPX-generated values and values brought into the
   defining module by [include] are outside this source-level census.

   Types (gh-ocannl-1009) are censused by one conservative rule: a top-level type declaration in the
   same modules whose NAME is mentioned nowhere in the tree but its own declaration -- in no type
   path of any implementation or interface, and in no spelled value its deriving generates -- is
   reported. That is how [Train.example_train_result] would have been caught: it shipped for a year
   with its name in two proposals' prose and nowhere else. The rule's boundary is stated, not
   accidental. It is a name count, not a resolution: a record label or variant constructor is never
   resolved to its type, so a type used only through them reads as unmentioned (a loud false
   refusal, exempted with that reason), and any same-named type path anywhere credits it (a quiet
   false negative). Prose never mentions a type, so a stale doc comment cannot keep one alive.

   Every pre-existing zero-reference value is an exact [Module.value] exemption below, and every
   pre-existing unmentioned type an exact [Module.type_name] one. A new implicit export or
   unmentioned type fails rather than silently extending that baseline; an exemption that gains a
   reference also fails stale, so cleanup cannot leave a permanent hole. *)

open Base
open Stdio

(* Every file this scan reads arrives as a `@<path>` response file, because the list is longer than
   a Windows command line may be; see [Test_utils.Scan_argv]. *)
let argv = Test_utils.Scan_argv.expand Stdlib.Sys.argv

module Read = Test_utils.Config_key_scan
module Scan = Test_utils.Dead_export_scan
module Dune = Test_utils.Dune_stanza_scan

(* Filled from the first live census. Every unannotated entry names one exact implicit export and
   shares the reason stated above: it predates the ratchet and needs an explicit interface or a
   usage decision. A value that goes zero-reference later carries its own reason where it sits. *)
let exempt_zero_reference_exports =
  [
    "Backend_impl.next_global_device_id";
    "Backend_intf.compare_hardware_limits";
    "Backend_intf.compare_mma_capability";
    "Backend_intf.compare_mma_input_format";
    "Backend_intf.compare_mma_staged_layout";
    "Backend_intf.equal_hardware_limits";
    "Backend_intf.equal_mma_capability";
    (* Not pre-existing. [Backend_intf.equal_mma_format_triple] and [advertises_mma_format] -- the
       typed way to interrogate the MMA seam of gh-ocannl-822 -- absorbed what used to be open-coded
       per-constructor comparisons at the call sites, which were this derived equality's only
       external references. It stays derived because the record equalities exempted above are
       generated from it, and asking the descriptor is what callers should reach for instead. *)
    "Backend_intf.equal_mma_input_format";
    "Backend_intf.equal_mma_staged_layout";
    "Backend_intf.hardware_limits_of_sexp";
    "Backend_intf.mma_capability_of_sexp";
    "Backend_intf.mma_input_format_of_sexp";
    "Backend_intf.mma_staged_layout_of_sexp";
    "C_syntax.c_float_literal";
    "C_syntax.c_keywords";
    "C_syntax.c_stdlib_idents";
    "C_syntax.c_stdlib_macros";
    "C_syntax.compare_mma_rendering";
    "C_syntax.compare_peel_site";
    "C_syntax.compare_peel_skip";
    "C_syntax.compare_peel_verdict";
    "C_syntax.compare_tensorization";
    "C_syntax.compare_volatility_site";
    "C_syntax.empty_mma_summary";
    "C_syntax.empty_peel_summary";
    "C_syntax.empty_volatility_summary";
    "C_syntax.equal_peel_skip";
    "C_syntax.extract_idents";
    "C_syntax.is_f32_tie";
    "C_syntax.is_tensorized_rendering";
    "C_syntax.log_declines";
    "C_syntax.mma_census_enabled";
    "C_syntax.mma_rendering_of_sexp";
    "C_syntax.op_syntax_idents";
    "C_syntax.peel_site_of_sexp";
    "C_syntax.peel_skip_of_sexp";
    "C_syntax.peel_verdict_of_sexp";
    "C_syntax.summarize_peel_census";
    "C_syntax.summarize_volatility_census";
    "C_syntax.tensorization_of_sexp";
    "C_syntax.volatility_site_of_sexp";
    "Lexer.buffered_token";
    "Lexer.multichar_token";
    "Lexer.single_char_token";
    "Ndarray.adjust_idx_for_padding";
    "Ndarray.big_ptr_to_string";
    "Ndarray.bigarray_start_not_managed";
    "Ndarray.c_ptr_to_string";
    "Ndarray.compare";
    "Ndarray.compute_end_idx";
    "Ndarray.count_logical_elems";
    "Ndarray.create_bigarray";
    "Ndarray.create_bigarray_of_prec";
    "Ndarray.decoded_count";
    "Ndarray.default_kind";
    "Ndarray.fill_from_float";
    "Ndarray.float_to_uint32";
    "Ndarray.float_to_uint64";
    "Ndarray.fold_bigarray";
    "Ndarray.get_voidptr_not_managed";
    "Ndarray.hash";
    "Ndarray.hash_fold_t";
    "Ndarray.hash_t";
    "Ndarray.linear_offset_of_idx";
    "Ndarray.log_debug_info";
    "Ndarray.mappable_file_region";
    "Ndarray.mapped_count";
    "Ndarray.precision_string";
    "Ndarray.precision_to_bigarray_kind";
    "Ndarray.ptr_to_string_hum";
    "Ndarray.to_native";
    "Ndarray.two_pow_63";
    "Ndarray.uint32_to_float";
    "Ndarray.uint64_to_float";
    "Ndarray.used_memory";
    "Numerics.bf16_mode_of_sexp";
    "Numerics.compare";
    "Numerics.compare_bf16_mode";
    "Numerics.compare_fp16_mode";
    "Numerics.default";
    "Numerics.equal";
    "Numerics.fp16_mode_of_sexp";
    "Numerics.policy";
    "Numerics.t_of_sexp";
    "Operation.add";
    "Operation.centered_uniform1_param_init";
    "Operation.centered_uniform_param_init";
    "Operation.compose_op_of_spec";
    "Operation.concat";
    "Operation.concat_sum";
    "Operation.cos";
    "Operation.default_uniform_param_init";
    "Operation.deinterleave_even";
    "Operation.deinterleave_odd";
    "Operation.einmax1";
    "Operation.embed_dim";
    "Operation.embed_self_id";
    "Operation.embed_symbol";
    "Operation.eq";
    "Operation.exp";
    "Operation.exp2";
    "Operation.fma";
    "Operation.grad";
    "Operation.interleave";
    "Operation.is_prohibit_grad";
    "Operation.le";
    "Operation.log";
    "Operation.log2";
    "Operation.log_2";
    "Operation.lt";
    "Operation.matmul";
    "Operation.mul";
    "Operation.ne";
    "Operation.neg";
    "Operation.not";
    "Operation.offsets";
    "Operation.outer_sum";
    "Operation.pin_counter_spec";
    "Operation.pointdiv";
    "Operation.pointpow";
    "Operation.range_of_shape";
    "Operation.rebatch";
    "Operation.recip";
    "Operation.recip_sqrt";
    "Operation.relu";
    "Operation.reshape";
    "Operation.sat01";
    "Operation.sin";
    "Operation.slice";
    "Operation.sqrt";
    "Operation.stack";
    "Operation.stop_gradient";
    "Operation.stretch";
    "Operation.sub";
    "Operation.tanh";
    "Operation.threefry4x32";
    "Operation.threefry4x32_crypto";
    "Operation.threefry4x32_light";
    "Operation.transpose_op_of_spec";
    "Operation.tropical";
    "Operation.uint4x32_to_prec_uniform";
    "Operation.uint4x32_to_prec_uniform1";
    "Operation.uniform1";
    "Operation.uniform_at";
    "Operation.uniform_at1";
    "Operation.wrap";
    "Ops.bfloat16_to_uint4x32";
    "Ops.binop_conditionality_of_sexp";
    "Ops.binop_of_sexp";
    "Ops.byte_to_uint4x32";
    "Ops.c_ptr_to_string";
    "Ops.compare_binop_conditionality";
    "Ops.compare_op";
    "Ops.compare_ternop_conditionality";
    "Ops.compare_voidptr";
    "Ops.double_to_uint4x32";
    "Ops.equal_voidptr";
    "Ops.equal_binop_conditionality";
    "Ops.equal_op";
    "Ops.equal_ternop_conditionality";
    "Ops.fp8_to_uint4x32";
    "Ops.half_to_uint4x32";
    "Ops.hum_typ_of_prec";
    "Ops.int32_to_uint4x32";
    "Ops.interpret_ternop";
    "Ops.is_assign_op";
    "Ops.is_binop_infix";
    "Ops.op_of_sexp";
    "Ops.precision_to_string";
    "Ops.ptr_to_string_hum";
    "Ops.single_to_uint4x32";
    "Ops.ternop_conditionality_of_sexp";
    "Ops.ternop_of_sexp";
    "Ops.uint16_to_uint4x32";
    "Ops.uint32_to_uint4x32";
    "Ops.uint64_to_uint4x32";
    "Ops.unop_of_sexp";
    "Ops.vec_unop_of_sexp";
    "Ppx_cd.args_for";
    "Ppx_cd.assignment";
    "Ppx_cd.compare_slots";
    "Ppx_cd.empty_comp";
    "Ppx_cd.empty_tns";
    "Ppx_cd.equal_projections_slot";
    "Ppx_cd.guess_pun_hint";
    "Ppx_cd.handle_cases";
    "Ppx_cd.is_unknown";
    "Ppx_cd.make_vb";
    "Ppx_cd.prod_slot_tensor_dims";
    "Ppx_cd.project_p_dims";
    "Ppx_cd.project_p_slot";
    "Ppx_cd.reduce_res_vbs";
    "Ppx_cd.setup_array";
    "Ppx_cd.slot_permutation_suffix";
    "Ppx_cd.slot_to_string";
    "Ppx_cd.translate";
    "Ppx_extend_dsls.transform_dsl_binding";
    "Ppx_ocannl.rules";
    "Ppx_op.dsl_fn";
    "Ppx_op.dsl_open_o";
    "Ppx_op.dsl_path";
    "Ppx_op.is_ndarray_constant_expr";
    "Ppx_op.make_p";
    "Ppx_op.make_vb";
    "Ppx_op.make_vb_nd";
    "Ppx_op.translate_block_tensor";
    "Ppx_op.translate_tdsl";
    "Ppx_shared.axes_or_dims_arg";
    "Ppx_shared.axis_basis_of_type";
    "Ppx_shared.dim_spec_to_string";
    "Ppx_shared.flatten_str";
    "Ppx_shared.non_alphanum_regexp";
    "Ppx_shared.operators";
    "Ppx_shared.opt_pat2string";
    "Ppx_shared.string_literal";
    "Ppx_shared.string_of_constant";
    "Ppx_shared.string_of_pat";
    "Ppx_shared.translate_str";
    "Schedulers.cpu_mma_limits";
    "Tnode.bounds_state_of_sexp";
    "Tnode.bounds_scan_worthwhile";
    "Tnode.collapse_consecutive";
    "Tnode.current_namespace";
    "Tnode.compare_memory_mode";
    "Tnode.delayed_prec_of_sexp";
    "Tnode.equal_bounds_state";
    "Tnode.equal_delayed_prec";
    "Tnode.equal_memory_mode";
    "Tnode.fresh_uid";
    "Tnode.hash_fold_t";
    "Tnode.hash_t";
    "Tnode.header";
    "Tnode.initial_default_prec";
    "Tnode.is_alphanum_";
    "Tnode.known_non_virtual";
    "Tnode.known_not_materialized";
    "Tnode.log_accessible_headers";
    "Tnode.memory_mode_of_sexp";
    "Tnode.most_local_materialized_mode";
    "Tnode.next_uid";
    "Tnode.prec_of_dalayed";
    "Tnode.propose_bounds";
    "Tnode.scan_host_bounds";
    "Tnode.transition_memory_mode";
    "Tnode.validate_padded_numel_contract";
    "Utils.accessed_global_args";
    "Utils.artifacts_subdir";
    "Utils.captured_log_processors";
    "Utils.clean_filename";
    "Utils.compare_requirement";
    "Utils.config_table_of_lines";
    (* gh-ocannl-604: bootstrap resolution and the sourced values carried from startup to its
       deferred trace are intentionally internal, replacing the old unsourced bootstrap reader.
       Utils has no .mli; publishing these staging details is not part of its consumer API. *)
    "Utils.resolve_bootstrap_config";
    "Utils.no_config_file_resolution";
    "Utils.early_log_config_sourcing_resolution";
    "Utils.log_config_sourcing_resolution";
    "Utils.suppress_welcome_message_resolution";
    "Utils.profile_selection";
    (* Not pre-existing. The C stub behind [Utils.c_stderr_detached] (gh-ocannl-1031): the module
       calls it once at its own initialization, and what the rest of the tree reads is the resulting
       boolean, not the stub. Publishing the stub is still right -- a caller that has taken fd 2
       over for its own reasons can redo the detachment -- but nothing in the tree needs to. *)
    "Utils.detach_c_stderr";
    "Utils.default_indent";
    "Utils.doc_of_sexp";
    "Utils.enable_runtime_debug";
    "Utils.ensure_artifacts_dir";
    "Utils.env_var_reserved_prefixes";
    "Utils.equal_config_level";
    "Utils.filename_concat";
    "Utils.filename_of_parts";
    "Utils.filename_parts";
    "Utils.flush_c_streams";
    "Utils.get_debug_output_channel";
    "Utils.header_sep";
    "Utils.input_line";
    "Utils.input_scan_line";
    "Utils.!@";
    "Utils.log_config_sourcing";
    "Utils.log_files_dir";
    "Utils.log_trace_tree";
    "Utils.never_capture_stdout";
    "Utils.normalize_exponent";
    "Utils.original_log_level";
    "Utils.pair";
    "Utils.parallel_merge";
    (* Not pre-existing: the third profile payload (gh-ocannl-719), listed like the two before it --
       named only through [Utils.profile_payloads]. *)
    "Utils.approximate_profile_payload";
    "Utils.performance_profile_payload";
    "Utils.profile_ineligible_keys";
    (* Not pre-existing: the per-key half of [Utils.profile_payload_sources] (gh-ocannl-719),
       top-level only because the config-key scan's forwarding exemption does not reach a lambda. *)
    "Utils.profile_key_source";
    "Utils.profile_lookup";
    "Utils.requirement_of_sexp";
    "Utils.reproducible_profile_payload";
    "Utils.same_env_name";
    "Utils.sexp_deep_mem";
    "Utils.settings_of_sexp";
    "Utils.split_with_seps";
    "Utils.str_nonempty";
    (* gh-ocannl-1009 widened the census to lib/, the user-facing recipe library, where these
       implicit exports have no caller in the tree. Unlike the entries above, most are not helpers
       leaked by a missing interface: [Nn_blocks]' architectures and initializers and [Train]'s
       entry points are the surface lib/ exists to offer, and some -- [normal], [kaiming], [xavier]
       -- are reached through [Nn_blocks.DSL_modules] re-exports this census does not follow. Which
       of them an interface should publish, and which it should hide, is gh-ocannl-1010's decision
       (lib/ has no interfaces); this block is its census. *)
    "Calibrate.named";
    "Nn_blocks.avg_pool2d";
    "Nn_blocks.batch_norm2d";
    "Nn_blocks.box_muller";
    "Nn_blocks.conv_bn_relu";
    "Nn_blocks.cross_attention";
    "Nn_blocks.decoder_only_block";
    "Nn_blocks.dropout";
    "Nn_blocks.global_avg_pool2d";
    "Nn_blocks.kaiming";
    "Nn_blocks.kaiming_at";
    "Nn_blocks.kaiming_impl";
    "Nn_blocks.mobile_cnn";
    "Nn_blocks.multi_head_att_workshop";
    "Nn_blocks.normal";
    "Nn_blocks.normal1";
    "Nn_blocks.normal_at";
    "Nn_blocks.normal_at1";
    "Nn_blocks.reduce_specified_axes";
    "Nn_blocks.resnet_block";
    "Nn_blocks.set_uint32_id";
    "Nn_blocks.sokoban_cnn";
    "Nn_blocks.transformer_decoder";
    "Nn_blocks.transformer_decoder_block";
    "Nn_blocks.transformer_encoder";
    "Nn_blocks.transformer_encoder_block";
    "Nn_blocks.vgg_block";
    "Nn_blocks.xavier";
    "Nn_blocks.xavier_at";
    "Nn_blocks.xavier_impl";
    "Parallel.host_get";
    "Parallel.schedule";
    "Train.compile_with_model_gate";
    "Train.compile_within_budget";
    "Train.decision_lowering_digest";
    "Train.dump_cd_file";
    "Train.embedded_nodes";
    "Train.ensure_printable";
    "Train.filter_out_grad_zeroing";
    "Train.fit_memory_budget";
    "Train.params_for";
    "Train.placement_arm_name";
    "Train.placement_decision_lists";
    "Train.run_once";
    (* gh-ocannl-1085: until then an [include M] credited every value of [M], so these were
       invisible; now a use must spell the value through [M] or through a module including it. Not
       one of them has such a use. [Datatypes.hash_fold_safe_lazy] is live nonetheless: [Row]'s
       [[@@deriving hash]] over [int Utils.safe_lazy] calls it, and this census does not model the
       [hash] deriving's references. *)
    "Datatypes.hash_fold_safe_lazy";
    (* Derived for types [Einsum_parser] republishes through [include module type of Einsum_types];
       no caller compares or parses them. Narrowing the derivings would narrow that interface
       too. *)
    "Einsum_types.axis_map_of_sexp";
    "Einsum_types.axis_spec_of_sexp";
    "Einsum_types.compare_axis_map";
    "Einsum_types.compare_axis_spec";
    "Einsum_types.compare_conv_spec";
    "Einsum_types.compare_parsed_axis_labels";
    "Einsum_types.compare_use_padding_spec";
    "Einsum_types.conv_spec_of_sexp";
    "Einsum_types.parsed_axis_labels_of_sexp";
    "Einsum_types.__use_padding_spec_of_sexp__";
    "Einsum_types.use_padding_spec_of_sexp";
    (* Helpers of the sketch families (gh-ocannl-580), called only inside their own module, which
       [autotune.ml] includes and [autotune.mli] publishes selectively. They leak because
       [sketch_families.ml] has no interface; that interface is the fix, not a removal. *)
    "Sketch_families.accesses_by_statement";
    "Sketch_families.batch_grid_twin_ok";
    "Sketch_families.batch_hoist_swaps";
    "Sketch_families.blocks_of";
    "Sketch_families.classify_matmul";
    "Sketch_families.companion_coverage_unsupported";
    "Sketch_families.companion_geometry";
    "Sketch_families.companion_role_ops";
    "Sketch_families.conv_aligned_grid";
    "Sketch_families.conv_axis_equal";
    "Sketch_families.conv_mma_scope";
    "Sketch_families.conv_real_stmts";
    "Sketch_families.conv_site_equal";
    "Sketch_families.conv_split_row_current";
    "Sketch_families.conv_tail_loop_syms";
    "Sketch_families.cpu_conv_sketch_schedule";
    "Sketch_families.cpu_grid_rendering_disabled";
    "Sketch_families.cpu_mma_pack_sketch_schedule";
    "Sketch_families.cpu_mma_sketch_schedule";
    "Sketch_families.cpu_sketch_schedule";
    "Sketch_families.decided_choice";
    "Sketch_families.detect_conv_affine";
    "Sketch_families.detect_conv_procedural";
    "Sketch_families.detect_matmul_affine";
    "Sketch_families.detect_matmul_procedural";
    "Sketch_families.epilogue_tail_loop_syms";
    "Sketch_families.fma_form";
    "Sketch_families.gpu_conv_sketch_schedule";
    "Sketch_families.gpu_mma_sketch_schedule";
    "Sketch_families.gpu_sketch_schedule";
    "Sketch_families.hoistable";
    "Sketch_families.idx_coeff";
    "Sketch_families.idx_mentions";
    "Sketch_families.interval_axis";
    "Sketch_families.k_blocks";
    "Sketch_families.k_extent_label";
    "Sketch_families.launch_geometry_refutation";
    "Sketch_families.loop_axis_types";
    "Sketch_families.matmul_batch_loops";
    "Sketch_families.matmul_chain_roles";
    "Sketch_families.matmul_coverage_witness";
    "Sketch_families.matmul_family_tree";
    "Sketch_families.matmul_flavor_tree";
    "Sketch_families.matmul_site_chain";
    "Sketch_families.matmul_site_equal";
    "Sketch_families.max_grid_fold_extent";
    "Sketch_families.mma_acc_format_of_prec";
    "Sketch_families.mma_input_formats_of_prec";
    "Sketch_families.mma_scope_of_reduction_extents";
    "Sketch_families.mma_staged_layout_for_precisions";
    "Sketch_families.nest_loop_syms";
    "Sketch_families.pad_composition_ok";
    "Sketch_families.pad_to";
    "Sketch_families.path_head";
    "Sketch_families.predicted_launch_geometry";
    "Sketch_families.reorder_swaps";
    "Sketch_families.seeding_limits";
    "Sketch_families.serial_kernel_of";
    "Sketch_families.serial_nest_of";
    "Sketch_families.sink";
    "Sketch_families.site_batch_ops";
    "Sketch_families.sketch_schedule_unchecked";
    "Sketch_families.strip_stmts";
    "Sketch_families.unit_axis";
    "Sketch_families.wide_acc_withholding";
    "Sketch_families.wide_acc_withholds";
    "Sketch_families.zero_expansion_witness";
    "Sketch_families.zero_geometry";
  ]

(* gh-ocannl-1009: the type census, filled from its first run. Every entry is a live type the
   name-occurs-once rule cannot see live: its values are built and taken apart through its
   constructors or record labels alone -- rank-2 wrappers such as [Ndarray.apply_as_bigarray]
   destructured as [{ f }], variants matched by constructor -- and the census does not resolve a
   constructor or label to its type (the support module's header says why). Annotating a use site
   with the type's name would take the entry off this list. *)
let exempt_unmentioned_types =
  [
    "Mixed_prec.twin_placement";
    "Ndarray.apply2_as_bigarray";
    "Ndarray.apply_as_bigarray";
    "Ndarray.apply_with_prec";
    "Nn_blocks.position_embedding";
    "Ops.apply_prec";
    "Ops.prec_family";
    "Parallel.handle";
    "Parallel.reduction";
    "Train.placement_arm";
    "Utils.config_source";
    "Utils.config_token";
    "Utils.env_var_class";
    "Utils.requirement";
    "Utils.settings";
  ]

let in_scan_root path =
  let directory = Stdlib.Filename.dirname path in
  List.mem [ "arrayjit/lib"; "tensor"; "lib" ] directory ~equal:String.equal

let require_implementations ~fail implementations =
  if List.is_empty implementations then (
    fail "no .mli-less implementation modules found under arrayjit/lib, tensor or lib";
    false)
  else true

let exports_or_refusal ~fail ~source contents =
  match Scan.exports_of_source ~source contents with
  | exports -> exports
  | exception exn ->
      fail
        (Printf.sprintf "%s does not parse as OCaml, so this scan cannot vouch for it: %s" source
           (Exn.to_string exn));
      []

let type_counts_or_refusal ~fail ~type_exports ~implementations ~interfaces =
  match Scan.type_mention_counts ~type_exports ~implementations ~interfaces with
  | counts -> counts
  | exception exn ->
      fail
        (Printf.sprintf
           "a source of the type census does not parse, so its mention counts are unknown: %s"
           (Exn.to_string exn));
      Hashtbl.create (module String)

let references_or_refusal ~fail ~exports ~sources =
  match Scan.references ~exports ~sources with
  | references -> references
  | exception exn ->
      fail
        (Printf.sprintf "an OCaml source does not parse, so this scan cannot vouch for it: %s"
           (Exn.to_string exn));
      []

let refusal_control () =
  let source = "test/operations/dead_export_scan.ml" in
  let case label ~format run =
    let refused = ref false in
    let fail _message =
      refused := true;
      Test_utils.Refusal_control_manifest.observe_failure ~source ~format
    in
    run fail;
    Verdict.p label !refused
  in
  case "an empty implementation census reaches its refusal"
    ~format:"no .mli-less implementation modules found under arrayjit/lib, tensor or lib"
    (fun fail -> ignore (require_implementations ~fail [] : bool));
  case "an invalid implementation reaches the export-parser refusal"
    ~format:"%s does not parse as OCaml, so this scan cannot vouch for it: %s" (fun fail ->
      ignore (exports_or_refusal ~fail ~source:"arrayjit/lib/bad.ml" "let =" : Scan.export list));
  let exports = Scan.exports_of_source ~source:"arrayjit/lib/sample.ml" "let value = 1" in
  case "an invalid consumer reaches the reference-parser refusal"
    ~format:"an OCaml source does not parse, so this scan cannot vouch for it: %s" (fun fail ->
      ignore
        (references_or_refusal ~fail ~exports ~sources:[ ("consumer.ml", "let =") ]
          : Scan.reference list));
  let type_exports = Scan.type_exports_of_source ~source:"arrayjit/lib/sample.ml" "type t = T" in
  case "an invalid interface reaches the type-census refusal"
    ~format:"a source of the type census does not parse, so its mention counts are unknown: %s"
    (fun fail ->
      ignore
        (type_counts_or_refusal ~fail ~type_exports ~implementations:[]
           ~interfaces:[ ("consumer.mli", "val") ]
          : (string, int) Hashtbl.t));
  Test_utils.Refusal_control_manifest.print source

let () =
  if Array.length argv = 2 && String.equal argv.(1) "--refusal-control" then (
    refusal_control ();
    Stdlib.exit 0);
  if Array.length argv < 2 then (
    eprintf "Usage: %s <workspace_root> <source...>\n" argv.(0);
    Stdlib.exit 1);
  let base = Dune.base_dir argv.(1) in
  let arguments =
    Array.to_list (Array.subo argv ~pos:2)
    |> List.map ~f:(fun path -> (Dune.repo_relative base path, path))
  in
  let on_disk = Map.of_alist_reduce (module String) arguments ~f:(fun first _ -> first) in
  let source_paths = Read.sources_among (List.map arguments ~f:fst) in
  let sources =
    List.map source_paths ~f:(fun source ->
        (source, In_channel.read_all (Map.find_exn on_disk source)))
  in
  let interfaces =
    List.filter (List.map arguments ~f:fst) ~f:(String.is_suffix ~suffix:".mli")
    |> Set.of_list (module String)
  in
  let implementations =
    List.filter sources ~f:(fun (source, _) -> in_scan_root source)
    |> List.filter ~f:(fun (source, _) ->
        match String.chop_suffix source ~suffix:".ml" with
        | Some stem -> not (Set.mem interfaces (stem ^ ".mli"))
        | None -> false)
  in
  if not (require_implementations ~fail:Verdict.fail implementations) then Stdlib.exit 1;
  let exports =
    List.concat_map implementations ~f:(fun (source, contents) ->
        exports_or_refusal ~fail:Verdict.fail ~source contents)
  in
  let references = references_or_refusal ~fail:Verdict.fail ~exports ~sources in
  let counts = Scan.counts ~exports references in
  let exemptions = Set.of_list (module String) exempt_zero_reference_exports in
  let zero_reference =
    List.filter exports ~f:(fun export -> Hashtbl.find_exn counts (Scan.export_key export) = 0)
  in
  let offenders =
    List.filter zero_reference ~f:(fun export -> not (Set.mem exemptions (Scan.export_key export)))
  in
  let stale =
    List.filter exempt_zero_reference_exports ~f:(fun key ->
        match Hashtbl.find counts key with Some 0 -> false | Some _ | None -> true)
  in
  List.iter offenders ~f:(fun export ->
      eprintf
        "%s:%d: %s has no external reference; add an .mli that hides or deliberately publishes it, \
         remove it, or add the exact name to exempt_zero_reference_exports with a reasoned decision\n"
        export.source export.line (Scan.export_key export));
  List.iter stale ~f:(fun key ->
      eprintf
        "%s is a stale dead-export exemption: the value is now referenced or no longer exported\n"
        key);
  eprintf "Scanned %d .mli-less modules, %d source-declared exports, and %d external references.\n"
    (List.length implementations) (List.length exports) (List.length references);
  Verdict.p_empty "every zero-reference implicit export is named" ~over:exports offenders;
  Verdict.p "named dead-export exemptions are unique"
    (Set.length exemptions = List.length exempt_zero_reference_exports);
  Verdict.p_empty "every named dead-export exemption remains necessary"
    ~over:exempt_zero_reference_exports stale;
  let type_exports =
    List.concat_map implementations ~f:(fun (source, contents) ->
        Scan.type_exports_of_source ~source contents)
  in
  let interface_sources =
    Scan.interfaces_among (List.map arguments ~f:fst)
    |> List.map ~f:(fun source -> (source, In_channel.read_all (Map.find_exn on_disk source)))
  in
  let type_counts =
    type_counts_or_refusal ~fail:Verdict.fail ~type_exports ~implementations:sources
      ~interfaces:interface_sources
  in
  let type_exemptions = Set.of_list (module String) exempt_unmentioned_types in
  let type_offenders =
    List.filter type_exports ~f:(fun export ->
        let key = Scan.type_export_key export in
        Option.value_map (Hashtbl.find type_counts key) ~default:false ~f:(( = ) 0)
        && not (Set.mem type_exemptions key))
  in
  let type_stale =
    List.filter exempt_unmentioned_types ~f:(fun key ->
        match Hashtbl.find type_counts key with Some 0 -> false | Some _ | None -> true)
  in
  List.iter type_offenders ~f:(fun (export : Scan.type_export) ->
      eprintf
        "%s:%d: type %s is mentioned nowhere but its own declaration; add an .mli that hides or \
         deliberately publishes it, remove it, or add the exact name to exempt_unmentioned_types \
         with a reasoned decision\n"
        export.source export.line (Scan.type_export_key export));
  List.iter type_stale ~f:(fun key ->
      eprintf
        "%s is a stale unmentioned-type exemption: the type is now mentioned or no longer declared\n"
        key);
  eprintf "Censused %d top-level type declarations in the same modules.\n"
    (List.length type_exports);
  Verdict.p_empty "every type mentioned only by its own declaration is named" ~over:type_exports
    type_offenders;
  Verdict.p "named unmentioned-type exemptions are unique"
    (Set.length type_exemptions = List.length exempt_unmentioned_types);
  Verdict.p_empty "every named unmentioned-type exemption remains necessary"
    ~over:exempt_unmentioned_types type_stale;
  Test_utils.Refusal_control_manifest.print "dead_export_scan.ml"
