(* gh-ocannl-806: a top-level helper in a module without an [.mli] is an exported value, even when
   its author meant it to be private. Two incidental hand sweeps found many such exports and still
   undercounted one family twofold. This repository scan makes the census mechanical for direct
   [*.ml] modules in [arrayjit/lib/] and [tensor/].

   The matching policy lives in [test/support/dead_export_scan.ml] and its synthetic negative
   controls. In particular, qualified paths through aliases count, and a bare identifier inside the
   lexical scope of [open M] counts conservatively. The latter can mistake a shadowing local for
   [M]'s value; that false-positive direction is deliberate for this first cut. An [include M]
   counts every value because it re-exports the interface. Source-declared [let] values starting
   with [_] are deliberately unused by OCaml convention and excluded by policy. Values generated by
   [of_sexp], [sexp], [compare], and [equal] derivings are exports too; the matching expression
   extensions count as references to the same generated names. The [sexp_of] converters, derived or
   hand-written, are excluded by policy (the support module's header says why): they are the
   debugging and observability entry point, and [ppx_minidebug]'s typed log annotations consume them
   invisibly to a source-level census. Other PPX-generated values and values brought into the
   defining module by [include] are outside this source-level census.

   Every pre-existing zero-reference value is an exact [Module.value] exemption below. A new
   implicit export fails rather than silently extending that baseline; an exemption that gains a
   reference also fails stale, so cleanup cannot leave a permanent hole. *)

open Base
open Stdio

(* Every file this scan reads arrives as a `@<path>` response file, because the list is longer than
   a Windows command line may be; see [Test_utils.Scan_argv]. *)
let argv = Test_utils.Scan_argv.expand Stdlib.Sys.argv

module Read = Test_utils.Config_key_scan
module Scan = Test_utils.Dead_export_scan
module Dune = Test_utils.Dune_stanza_scan

(* Filled from the first live census. Every unannotated entry names one exact implicit export and
   shares the reason stated above: it predates the ratchet and needs an explicit interface or a
   usage decision. A value that goes zero-reference later carries its own reason where it sits. *)
let exempt_zero_reference_exports =
  [
    "Backend_impl.next_global_device_id";
    "Backend_intf.compare_hardware_limits";
    "Backend_intf.compare_mma_capability";
    "Backend_intf.compare_mma_input_format";
    "Backend_intf.compare_mma_staged_layout";
    "Backend_intf.equal_hardware_limits";
    "Backend_intf.equal_mma_capability";
    (* Not pre-existing. [Backend_intf.equal_mma_format_triple] and [advertises_mma_format] -- the
       typed way to interrogate the MMA seam of gh-ocannl-822 -- absorbed what used to be open-coded
       per-constructor comparisons at the call sites, which were this derived equality's only
       external references. It stays derived because the record equalities exempted above are
       generated from it, and asking the descriptor is what callers should reach for instead. *)
    "Backend_intf.equal_mma_input_format";
    "Backend_intf.equal_mma_staged_layout";
    "Backend_intf.hardware_limits_of_sexp";
    "Backend_intf.mma_capability_of_sexp";
    "Backend_intf.mma_input_format_of_sexp";
    "Backend_intf.mma_staged_layout_of_sexp";
    "Builtins_cc.source";
    "C_syntax.all_precs";
    "C_syntax.c_float_literal";
    "C_syntax.c_keywords";
    "C_syntax.c_stdlib_idents";
    "C_syntax.c_stdlib_macros";
    "C_syntax.compare_mma_rendering";
    "C_syntax.compare_peel_site";
    "C_syntax.compare_peel_skip";
    "C_syntax.compare_peel_verdict";
    "C_syntax.compare_tensorization";
    "C_syntax.compare_volatility_site";
    "C_syntax.current_kernel_name";
    "C_syntax.empty_mma_summary";
    "C_syntax.empty_peel_summary";
    "C_syntax.empty_volatility_summary";
    "C_syntax.equal_peel_skip";
    "C_syntax.extract_idents";
    "C_syntax.is_f32_tie";
    "C_syntax.is_tensorized_rendering";
    "C_syntax.log_declines";
    "C_syntax.mma_census_enabled";
    "C_syntax.mma_rendering_of_sexp";
    "C_syntax.op_syntax_idents";
    "C_syntax.peel_site_of_sexp";
    "C_syntax.peel_skip_of_sexp";
    "C_syntax.peel_verdict_of_sexp";
    "C_syntax.summarize_peel_census";
    "C_syntax.summarize_volatility_census";
    "C_syntax.tensorization_of_sexp";
    "C_syntax.volatility_site_of_sexp";
    "Lexer.buffered_token";
    "Lexer.multichar_token";
    "Lexer.single_char_token";
    "Ndarray.adjust_idx_for_padding";
    "Ndarray.big_ptr_to_string";
    "Ndarray.bigarray_start_not_managed";
    "Ndarray.c_ptr_to_string";
    "Ndarray.compare";
    "Ndarray.compute_end_idx";
    "Ndarray.count_logical_elems";
    "Ndarray.create_bigarray";
    "Ndarray.create_bigarray_of_prec";
    "Ndarray.decoded_count";
    "Ndarray.default_kind";
    "Ndarray.fill_from_float";
    "Ndarray.float_to_uint32";
    "Ndarray.float_to_uint64";
    "Ndarray.fold_bigarray";
    "Ndarray.get_voidptr_not_managed";
    "Ndarray.hash";
    "Ndarray.hash_fold_t";
    "Ndarray.hash_t";
    "Ndarray.linear_offset_of_idx";
    "Ndarray.log_debug_info";
    "Ndarray.mappable_file_region";
    "Ndarray.mapped_count";
    "Ndarray.precision_string";
    "Ndarray.precision_to_bigarray_kind";
    "Ndarray.ptr_to_string_hum";
    "Ndarray.to_native";
    "Ndarray.two_pow_63";
    "Ndarray.uint32_to_float";
    "Ndarray.uint64_to_float";
    "Ndarray.used_memory";
    "Numerics.compare";
    "Numerics.compare_fp16_mode";
    "Numerics.default";
    "Numerics.equal";
    "Numerics.fp16_mode_of_sexp";
    "Numerics.policy";
    "Numerics.t_of_sexp";
    "Operation.add";
    "Operation.centered_uniform1_param_init";
    "Operation.centered_uniform_param_init";
    "Operation.compose_op_of_spec";
    "Operation.concat";
    "Operation.concat_sum";
    "Operation.cos";
    "Operation.default_uniform_param_init";
    "Operation.deinterleave_even";
    "Operation.deinterleave_odd";
    "Operation.einmax1";
    "Operation.embed_dim";
    "Operation.embed_self_id";
    "Operation.embed_symbol";
    "Operation.eq";
    "Operation.exp";
    "Operation.exp2";
    "Operation.fma";
    "Operation.grad";
    "Operation.interleave";
    "Operation.is_prohibit_grad";
    "Operation.le";
    "Operation.log";
    "Operation.log2";
    "Operation.log_2";
    "Operation.lt";
    "Operation.matmul";
    "Operation.mul";
    "Operation.ne";
    "Operation.neg";
    "Operation.not";
    "Operation.offsets";
    "Operation.outer_sum";
    "Operation.pin_counter_spec";
    "Operation.pointdiv";
    "Operation.pointpow";
    "Operation.range_of_shape";
    "Operation.rebatch";
    "Operation.recip";
    "Operation.recip_sqrt";
    "Operation.relu";
    "Operation.reshape";
    "Operation.sat01";
    "Operation.sin";
    "Operation.slice";
    "Operation.sqrt";
    "Operation.stack";
    "Operation.stop_gradient";
    "Operation.stretch";
    "Operation.sub";
    "Operation.tanh";
    "Operation.threefry4x32";
    "Operation.threefry4x32_crypto";
    "Operation.threefry4x32_light";
    "Operation.transpose_op_of_spec";
    "Operation.tropical";
    "Operation.uint4x32_to_prec_uniform";
    "Operation.uint4x32_to_prec_uniform1";
    "Operation.uniform1";
    "Operation.uniform_at";
    "Operation.uniform_at1";
    "Operation.wrap";
    "Ops.bfloat16_to_uint4x32";
    "Ops.binop_conditionality_of_sexp";
    "Ops.binop_of_sexp";
    "Ops.byte_to_uint4x32";
    "Ops.c_ptr_to_string";
    "Ops.compare_binop_conditionality";
    "Ops.compare_op";
    "Ops.compare_ternop_conditionality";
    "Ops.compare_voidptr";
    "Ops.double_to_uint4x32";
    "Ops.equal_voidptr";
    "Ops.equal_binop_conditionality";
    "Ops.equal_op";
    "Ops.equal_ternop_conditionality";
    "Ops.fp8_to_uint4x32";
    "Ops.half_to_uint4x32";
    "Ops.hum_typ_of_prec";
    "Ops.int32_to_uint4x32";
    "Ops.interpret_ternop";
    "Ops.is_assign_op";
    "Ops.is_binop_infix";
    "Ops.pack_prec";
    "Ops.op_of_sexp";
    "Ops.precision_to_string";
    "Ops.ptr_to_string_hum";
    "Ops.single_to_uint4x32";
    "Ops.ternop_conditionality_of_sexp";
    "Ops.ternop_of_sexp";
    "Ops.uint16_to_uint4x32";
    "Ops.uint32_to_uint4x32";
    "Ops.uint64_to_uint4x32";
    "Ops.unop_of_sexp";
    "Ops.vec_unop_of_sexp";
    "Ppx_cd.args_for";
    "Ppx_cd.assignment";
    "Ppx_cd.compare_slots";
    "Ppx_cd.empty_comp";
    "Ppx_cd.empty_tns";
    "Ppx_cd.equal_projections_slot";
    "Ppx_cd.guess_pun_hint";
    "Ppx_cd.handle_cases";
    "Ppx_cd.is_unknown";
    "Ppx_cd.make_vb";
    "Ppx_cd.prod_slot_tensor_dims";
    "Ppx_cd.project_p_dims";
    "Ppx_cd.project_p_slot";
    "Ppx_cd.reduce_res_vbs";
    "Ppx_cd.setup_array";
    "Ppx_cd.slot_permutation_suffix";
    "Ppx_cd.slot_to_string";
    "Ppx_cd.translate";
    "Ppx_extend_dsls.transform_dsl_binding";
    "Ppx_ocannl.rules";
    "Ppx_op.dsl_fn";
    "Ppx_op.dsl_open_o";
    "Ppx_op.dsl_path";
    "Ppx_op.is_ndarray_constant_expr";
    "Ppx_op.make_p";
    "Ppx_op.make_vb";
    "Ppx_op.make_vb_nd";
    "Ppx_op.translate_block_tensor";
    "Ppx_op.translate_tdsl";
    "Ppx_shared.axes_or_dims_arg";
    "Ppx_shared.axis_basis_of_type";
    "Ppx_shared.dim_spec_to_string";
    "Ppx_shared.flatten_str";
    "Ppx_shared.non_alphanum_regexp";
    "Ppx_shared.operators";
    "Ppx_shared.opt_pat2string";
    "Ppx_shared.string_literal";
    "Ppx_shared.string_of_constant";
    "Ppx_shared.string_of_pat";
    "Ppx_shared.translate_str";
    "Schedulers.cpu_mma_limits";
    "Tnode.bounds_state_of_sexp";
    "Tnode.bounds_scan_worthwhile";
    "Tnode.collapse_consecutive";
    "Tnode.current_namespace";
    "Tnode.compare_memory_mode";
    "Tnode.delayed_prec_of_sexp";
    "Tnode.equal_bounds_state";
    "Tnode.equal_delayed_prec";
    "Tnode.equal_memory_mode";
    "Tnode.fresh_uid";
    "Tnode.hash_fold_t";
    "Tnode.hash_t";
    "Tnode.header";
    "Tnode.initial_default_prec";
    "Tnode.is_alphanum_";
    "Tnode.known_non_virtual";
    "Tnode.known_not_materialized";
    "Tnode.log_accessible_headers";
    "Tnode.memory_mode_of_sexp";
    "Tnode.most_local_materialized_mode";
    "Tnode.next_uid";
    "Tnode.prec_of_dalayed";
    "Tnode.propose_bounds";
    "Tnode.scan_host_bounds";
    "Tnode.transition_memory_mode";
    "Tnode.validate_padded_numel_contract";
    "Utils.accessed_global_args";
    "Utils.artifacts_subdir";
    "Utils.captured_log_processors";
    "Utils.clean_filename";
    "Utils.compare_requirement";
    "Utils.config_table_of_lines";
    "Utils.default_indent";
    "Utils.describe_config_source";
    "Utils.doc_of_sexp";
    "Utils.enable_runtime_debug";
    "Utils.ensure_artifacts_dir";
    "Utils.env_var_reserved_prefixes";
    "Utils.equal_config_level";
    "Utils.filename_concat";
    "Utils.filename_of_parts";
    "Utils.filename_parts";
    "Utils.flush_c_streams";
    "Utils.get_debug_output_channel";
    "Utils.header_sep";
    "Utils.input_line";
    "Utils.input_scan_line";
    "Utils.!@";
    "Utils.log_config_sourcing";
    "Utils.log_config_sourcing_arg";
    "Utils.log_files_dir";
    "Utils.log_trace_tree";
    "Utils.never_capture_stdout";
    "Utils.normalize_exponent";
    "Utils.original_log_level";
    "Utils.pair";
    "Utils.parallel_merge";
    (* Not pre-existing: the third profile payload (gh-ocannl-719), listed like the two before it --
       named only through [Utils.profile_payloads]. *)
    "Utils.approximate_profile_payload";
    "Utils.parse_profile_payload";
    "Utils.performance_profile_payload";
    "Utils.profile_ineligible_keys";
    (* Not pre-existing: the per-key half of [Utils.profile_payload_sources] (gh-ocannl-719),
       top-level only because the config-key scan's forwarding exemption does not reach a lambda. *)
    "Utils.profile_key_source";
    "Utils.profile_lookup";
    "Utils.read_cmdline_or_env_var";
    "Utils.requirement_of_sexp";
    "Utils.reproducible_profile_payload";
    "Utils.same_env_name";
    "Utils.sexp_deep_mem";
    "Utils.settings_of_sexp";
    "Utils.split_with_seps";
    "Utils.str_nonempty";
  ]

let in_scan_root path =
  let directory = Stdlib.Filename.dirname path in
  String.equal directory "arrayjit/lib" || String.equal directory "tensor"

let require_implementations ~fail implementations =
  if List.is_empty implementations then (
    fail "no .mli-less implementation modules found under arrayjit/lib or tensor";
    false)
  else true

let exports_or_refusal ~fail ~source contents =
  match Scan.exports_of_source ~source contents with
  | exports -> exports
  | exception exn ->
      fail
        (Printf.sprintf "%s does not parse as OCaml, so this scan cannot vouch for it: %s" source
           (Exn.to_string exn));
      []

let references_or_refusal ~fail ~exports ~sources =
  match Scan.references ~exports ~sources with
  | references -> references
  | exception exn ->
      fail
        (Printf.sprintf "an OCaml source does not parse, so this scan cannot vouch for it: %s"
           (Exn.to_string exn));
      []

let refusal_control () =
  let source = "test/operations/dead_export_scan.ml" in
  let case label ~format run =
    let refused = ref false in
    let fail _message =
      refused := true;
      Test_utils.Refusal_control_manifest.observe_failure ~source ~format
    in
    run fail;
    Verdict.p label !refused
  in
  case "an empty implementation census reaches its refusal"
    ~format:"no .mli-less implementation modules found under arrayjit/lib or tensor" (fun fail ->
      ignore (require_implementations ~fail [] : bool));
  case "an invalid implementation reaches the export-parser refusal"
    ~format:"%s does not parse as OCaml, so this scan cannot vouch for it: %s" (fun fail ->
      ignore (exports_or_refusal ~fail ~source:"arrayjit/lib/bad.ml" "let =" : Scan.export list));
  let exports = Scan.exports_of_source ~source:"arrayjit/lib/sample.ml" "let value = 1" in
  case "an invalid consumer reaches the reference-parser refusal"
    ~format:"an OCaml source does not parse, so this scan cannot vouch for it: %s" (fun fail ->
      ignore
        (references_or_refusal ~fail ~exports ~sources:[ ("consumer.ml", "let =") ]
          : Scan.reference list));
  Test_utils.Refusal_control_manifest.print source

let () =
  if Array.length argv = 2 && String.equal argv.(1) "--refusal-control" then (
    refusal_control ();
    Stdlib.exit 0);
  if Array.length argv < 2 then (
    eprintf "Usage: %s <workspace_root> <source...>\n" argv.(0);
    Stdlib.exit 1);
  let base = Dune.base_dir argv.(1) in
  let arguments =
    Array.to_list (Array.subo argv ~pos:2)
    |> List.map ~f:(fun path -> (Dune.repo_relative base path, path))
  in
  let on_disk = Map.of_alist_reduce (module String) arguments ~f:(fun first _ -> first) in
  let source_paths = Read.sources_among (List.map arguments ~f:fst) in
  let sources =
    List.map source_paths ~f:(fun source ->
        (source, In_channel.read_all (Map.find_exn on_disk source)))
  in
  let interfaces =
    List.filter (List.map arguments ~f:fst) ~f:(String.is_suffix ~suffix:".mli")
    |> Set.of_list (module String)
  in
  let implementations =
    List.filter sources ~f:(fun (source, _) -> in_scan_root source)
    |> List.filter ~f:(fun (source, _) ->
        match String.chop_suffix source ~suffix:".ml" with
        | Some stem -> not (Set.mem interfaces (stem ^ ".mli"))
        | None -> false)
  in
  if not (require_implementations ~fail:Verdict.fail implementations) then Stdlib.exit 1;
  let exports =
    List.concat_map implementations ~f:(fun (source, contents) ->
        exports_or_refusal ~fail:Verdict.fail ~source contents)
  in
  let references = references_or_refusal ~fail:Verdict.fail ~exports ~sources in
  let counts = Scan.counts ~exports references in
  let exemptions = Set.of_list (module String) exempt_zero_reference_exports in
  let zero_reference =
    List.filter exports ~f:(fun export -> Hashtbl.find_exn counts (Scan.export_key export) = 0)
  in
  let offenders =
    List.filter zero_reference ~f:(fun export -> not (Set.mem exemptions (Scan.export_key export)))
  in
  let stale =
    List.filter exempt_zero_reference_exports ~f:(fun key ->
        match Hashtbl.find counts key with Some 0 -> false | Some _ | None -> true)
  in
  List.iter offenders ~f:(fun export ->
      eprintf
        "%s:%d: %s has no external reference; add an .mli that hides or deliberately publishes it, \
         remove it, or add the exact name to exempt_zero_reference_exports with a reasoned decision\n"
        export.source export.line (Scan.export_key export));
  List.iter stale ~f:(fun key ->
      eprintf
        "%s is a stale dead-export exemption: the value is now referenced or no longer exported\n"
        key);
  eprintf "Scanned %d .mli-less modules, %d source-declared exports, and %d external references.\n"
    (List.length implementations) (List.length exports) (List.length references);
  Verdict.p_empty "every zero-reference implicit export is named" ~over:exports offenders;
  Verdict.p "named dead-export exemptions are unique"
    (Set.length exemptions = List.length exempt_zero_reference_exports);
  Verdict.p_empty "every named dead-export exemption remains necessary"
    ~over:exempt_zero_reference_exports stale;
  Test_utils.Refusal_control_manifest.print "dead_export_scan.ml"
