(* Emits half_emulated.h for half_codec_exhaustive_stubs.c (gh-ocannl-985): the emulated fp16
   converters, taken from the definition table every C consumer reads (builtins_cc.ml, copied here
   as [Half_builtins_table] the way arrayjit/lib/gen_builtins copies it), so the sweep compiles the
   very text a compiler without [_Float16] compiles -- not a transcription of it.

   On every machine the fleet runs, [HAS_NATIVE_FLOAT16] is 1 and the table's emulated definitions
   are preprocessed away, both in the host stubs and in cc kernels. So this header pins the one
   switch the sweep needs: [HAS_NATIVE_FLOAT16] is defined as 0 in place of the table's detection,
   and everything else in the two converters' dependency closure is emitted verbatim, in table
   order. A converter that grows a dependency on another builtin gets it here with no edit; one
   whose guard stops being [HAS_NATIVE_FLOAT16] compiles to nothing, and the stub's link fails. *)

let roots = [ "half_to_float_emulated"; "float_to_half_emulated" ]
let switch = "HAS_NATIVE_FLOAT16"

let () =
  let table = Half_builtins_table.builtins in
  let find key =
    match List.find_opt (fun (k, _, _) -> String.equal k key) table with
    | Some entry -> entry
    | None -> failwith ("gen_half_emulated: no builtin named " ^ key)
  in
  let rec close acc key =
    if List.mem key acc then acc
    else
      let _, _, deps = find key in
      List.fold_left close (key :: acc) deps
  in
  let closure = List.fold_left close [] roots in
  if not (List.mem switch closure) then
    failwith ("gen_half_emulated: the emulated converters no longer depend on " ^ switch);
  print_endline "/* Generated by gen_half_emulated.exe from arrayjit/lib/builtins_cc.ml. */";
  print_endline "#ifndef HALF_CODEC_EMULATED_H";
  print_endline "#define HALF_CODEC_EMULATED_H";
  print_endline "#include <math.h>\n#include <stdint.h>\n#include <string.h>";
  List.iter
    (fun (key, definition, _) ->
      if List.mem key closure then
        if String.equal key switch then
          Printf.printf
            "\n\
             /* %s forced off: the emulated converters, whatever the compiler offers. */\n\
             #define %s 0\n"
            switch switch
        else print_string definition)
    table;
  print_endline "\n#endif"
