(* Emits a C header of converters taken from the definition table every C consumer reads (the
   stdlib-only [arrayjit.builtins_cc] library, which arrayjit/lib/gen_builtins links too), so an
   exhaustive codec sweep compiles the very text cc kernels and the host stubs compile -- not a
   transcription of it. Two users:

   - half_emulated.h for half_codec_exhaustive_stubs.c (gh-ocannl-985): the emulated fp16
   converters. On every machine the fleet runs, [HAS_NATIVE_FLOAT16] is 1 and the table's emulated
   definitions are preprocessed away, both in the host stubs and in cc kernels, so that header pins
   the one switch the sweep needs: [--force-off HAS_NATIVE_FLOAT16] defines it as 0 in place of the
   table's detection. - bf16_codec.h for bf16_codec_exhaustive_stubs.c (gh-ocannl-1069): the bf16
   converters and the vector narrowing/widening bridges, with no switch forced -- they are live code
   on every box.

   Usage: [gen_codec_header.exe --guard NAME [--force-off SWITCH] ROOT...]. Everything in the roots'
   dependency closure is emitted verbatim, in table order. A converter that grows a dependency on
   another builtin gets it here with no edit; one whose guard stops being the forced switch compiles
   to nothing, and the stub's link fails. *)

let () =
  let rec parse guard switch roots = function
    | "--guard" :: g :: rest -> parse (Some g) switch roots rest
    | "--force-off" :: s :: rest -> parse guard (Some s) roots rest
    | r :: rest -> parse guard switch (r :: roots) rest
    | [] -> (guard, switch, List.rev roots)
  in
  let guard, switch, roots = parse None None [] (List.tl (Array.to_list Sys.argv)) in
  let guard =
    match guard with Some g -> g | None -> failwith "gen_codec_header: --guard NAME is required"
  in
  if roots = [] then failwith "gen_codec_header: no converter named";
  let table = Builtins_cc.builtins in
  let find key =
    match List.find_opt (fun (k, _, _) -> String.equal k key) table with
    | Some entry -> entry
    | None -> failwith ("gen_codec_header: no builtin named " ^ key)
  in
  let rec close acc key =
    if List.mem key acc then acc
    else
      let _, _, deps = find key in
      List.fold_left close (key :: acc) deps
  in
  let closure = List.fold_left close [] roots in
  Option.iter
    (fun switch ->
      if not (List.mem switch closure) then
        failwith ("gen_codec_header: the converters no longer depend on " ^ switch))
    switch;
  print_endline "/* Generated by gen_codec_header.exe from arrayjit/lib/builtins_cc.ml. */";
  Printf.printf "#ifndef %s\n#define %s\n" guard guard;
  print_endline "#include <math.h>\n#include <stdint.h>\n#include <string.h>";
  List.iter
    (fun (key, definition, _) ->
      if List.mem key closure then
        if Some key = switch then
          Printf.printf "\n/* %s forced off, whatever the compiler offers. */\n#define %s 0\n" key
            key
        else print_string definition)
    table;
  print_endline "\n#endif"
