(* Exhaustive verification of the emulated fp16 converters, CPU-only (gh-ocannl-985).

   [float_to_half_emulated] and [half_to_float_emulated] are what a compiler without [_Float16]
   compiles, in cc kernels and in the host stubs. Every fleet box has [_Float16], so no shipped path
   reaches them there: the only thing between them and a silent wrong value on such a compiler is
   what checks them directly. gh-ocannl-981 was a curated corpus missing a whole rounding interval
   (everything strictly between 2^-25 and 2^-24 flushed to zero), so the check is every input.

   - [float_to_half_emulated] over all 2^32 f32 bit patterns against a rounding ORACLE -- the
   format's decode table plus the rule that a code owns the interval between the midpoints to its
   neighbours, ties to the even code, infinity taking part as the code after 0x7BFF -- and, where
   the compiler has [_Float16], against the native cast bit for bit. - [half_to_float_emulated] over
   all 65536 codes against the format's exact values, and against the native widening where there is
   one. - The two together: every non-NaN code survives a widen-and-narrow round trip.

   The sweep is in half_codec_exhaustive_stubs.c, which compiles the definition table's own text
   (half_emulated.h, generated by gen_half_emulated.exe). Under [@slow] because it takes seconds
   rather than milliseconds; [@check] still compiles it. *)

open Base

type sweep_buf =
  (int64, Stdlib.Bigarray.int64_elt, Stdlib.Bigarray.c_layout) Stdlib.Bigarray.Array1.t

external sweep_init : unit -> unit = "ocannl_half_sweep_init"
external sweep_narrow : int64 -> int64 -> sweep_buf -> unit = "ocannl_half_sweep_narrow"
external has_native : unit -> bool = "ocannl_half_has_native"
external emulated_widen : int -> float = "ocannl_half_emulated_widen"
external emulated_narrow : float -> int = "ocannl_half_emulated_narrow"
external native_widen : int -> float = "ocannl_half_native_widen"
external reference_decode : int -> float = "ocannl_half_reference_decode"

(* Mirrors the OUT_* offsets in half_codec_exhaustive_stubs.c. *)
let out_native = 0
let out_rounding = 1
let out_sign = 2
let out_special = 3
let out_reported = 4
let out_records = 5
let max_records = 8
let out_reached = out_records + (3 * max_records)
let reached_words = 1024
let out_len = out_reached + reached_words
let two_pow_32 = 0x1_0000_0000
let inf_code = 0x7C00
let qnan_code = 0x7E00

let fresh_buf () : sweep_buf =
  let b = Stdlib.Bigarray.Array1.create Stdlib.Bigarray.int64 Stdlib.Bigarray.c_layout out_len in
  Stdlib.Bigarray.Array1.fill b 0L;
  b

(* One contiguous range per domain, capped at 8 as in fp8_codec_exhaustive: the sweep is memory-free
   and scales linearly, so the cap only decides how much of a shared machine it takes. *)
let domains = Int.min 8 (Domain.recommended_domain_count ())

let run sweep total =
  let chunk = (total + domains - 1) / domains in
  let bufs = Array.init domains ~f:(fun _ -> fresh_buf ()) in
  let spawned =
    Array.init domains ~f:(fun i ->
        let base = i * chunk in
        let count = Int.max 0 (Int.min chunk (total - base)) in
        Domain.spawn (fun () -> sweep (Int64.of_int base) (Int64.of_int count) bufs.(i)))
  in
  Array.iter spawned ~f:Domain.join;
  bufs

let sum bufs i = Array.fold bufs ~init:0 ~f:(fun acc b -> acc + Int64.to_int_exn b.{i})

let reached bufs =
  Array.init reached_words ~f:(fun w ->
      Array.fold bufs ~init:0L ~f:(fun acc b -> Int64.bit_or acc b.{out_reached + w}))

(* The offender records, in chunk order, so a failing run names the same inputs every time. *)
let records bufs =
  Array.concat_map bufs ~f:(fun b ->
      Array.init
        (Int64.to_int_exn b.{out_reported})
        ~f:(fun k ->
          let base = out_records + (3 * k) in
          (b.{base}, Int64.to_int_exn b.{base + 1}, Int64.to_int_exn b.{base + 2})))

let reason_name = function
  | 1 -> "the native _Float16 cast narrows it differently"
  | 2 -> "not the nearest code (ties to even)"
  | 3 -> "sign not carried over"
  | 4 -> "an infinity or NaN narrowed to the wrong code"
  | r -> Printf.sprintf "unknown reason %d" r

(* Offenders go to stderr with their exact bit patterns: what a failing run needs and what a passing
   golden must not carry. A native disagreement packs both codes ([native] << 16 | [emulated]). *)
let report_records rs =
  Array.iter rs ~f:(fun (bits, code, reason) ->
      if reason = 1 then
        Stdio.eprintf "narrowing: input 0x%08Lx -> emulated 0x%04x, native 0x%04x (%s)\n" bits
          (code land 0xFFFF) (code lsr 16) (reason_name reason)
      else Stdio.eprintf "narrowing: input 0x%08Lx -> 0x%04x (%s)\n" bits code (reason_name reason))

let report_counts bufs =
  List.iter
    [
      ("native disagreements", out_native);
      ("misroundings", out_rounding);
      ("sign losses", out_sign);
      ("infinities or NaNs on the wrong code", out_special);
    ]
    ~f:(fun (what, i) ->
      let n = sum bufs i in
      if n > 0 then Stdio.eprintf "narrowing: %d %s (not part of the golden)\n" n what)

let same a b = Int64.equal (Int64.bits_of_float a) (Int64.bits_of_float b)
let codes = List.range 0 0x10000
let is_nan_code c = c land 0x7C00 = 0x7C00 && c land 0x3FF <> 0

let () =
  sweep_init ();
  let native = has_native () in
  let on = "a compiler without _Float16" in
  Stdio.eprintf "native _Float16 cross-check: %b (not part of the golden)\n" native;
  let started = Unix.gettimeofday () in
  let narrow = run sweep_narrow two_pow_32 in
  Stdio.eprintf "narrowing sweep: %.1fs; %d domains (not part of the golden)\n"
    (Unix.gettimeofday () -. started)
    domains;
  report_counts narrow;
  report_records (records narrow);
  Stdio.printf "fp16 emulated converters, exhaustive sweep\n";
  Stdio.printf "  f32 bit patterns narrowed: %d\n" two_pow_32;
  Stdio.printf "  half codes widened: %d\n" (List.length codes);

  Verdict.p
    "float_to_half_emulated rounds every finite f32 input to the nearest half code, ties to even, \
     overflowing to infinity from 65520 up"
    (sum narrow out_rounding = 0);
  Verdict.p
    "float_to_half_emulated carries the sign of every f32 input over, zeros and NaNs included"
    (sum narrow out_sign = 0);
  Verdict.p
    "every infinite f32 input narrows to 0x7C00 and every NaN to the quiet NaN 0x7E00, keeping its \
     sign"
    (sum narrow out_special = 0);
  Verdict.gated ~aggregation:`Environment ~when_:native ~on
    "float_to_half_emulated agrees with the native _Float16 cast on every f32 input, NaNs up to \
     payload"
    (sum narrow out_native = 0);

  (* Non-vacuity: "no misrounding" read together with "and every code is reachable" -- a converter
     that flushed a range of subnormals, the gh-ocannl-981 shape, would lose codes here even if the
     oracle were somehow satisfied. The NaN payloads other than the canonical quiet one are never
     produced: every NaN narrows to 0x7E00 (or its negative). *)
  let reachable = reached narrow in
  let is_reached c =
    not (Int64.equal 0L (Int64.bit_and reachable.(c / 64) (Int64.shift_left 1L (c % 64))))
  in
  let expected_reachable c = c land 0x7FFF <= inf_code || c land 0x7FFF = qnan_code in
  Stdio.printf "  distinct half codes produced by narrowing: %d\n" (List.count codes ~f:is_reached);
  Verdict.p_all
    "narrowing f32 reaches every finite and infinite half code and the quiet NaN, and nothing else"
    codes ~min:0x10000 ~f:(fun c -> Bool.equal (is_reached c) (expected_reachable c));

  (* Widening, all 65536 codes. The reference decode is the format read off its fields, computed in
     the stub next to the oracle -- so its monotonicity is also what licenses the oracle's use of
     midpoints. *)
  let widened = Array.of_list (List.map codes ~f:emulated_widen) in
  let decode_ok c =
    let m = c land 0x7FFF in
    let signed v = if c land 0x8000 <> 0 then Float.neg v else v in
    if m < inf_code then same widened.(c) (signed (reference_decode m))
    else if m = inf_code then Float.equal widened.(c) (signed Float.infinity)
    else Float.is_nan widened.(c)
  in
  Verdict.p_all
    "half_to_float_emulated widens all 65536 codes to their exact half values, signed zero \
     included, and every NaN code to a NaN"
    codes ~min:0x10000 ~f:decode_ok;
  Verdict.p_all
    "the format's decode is strictly increasing over the 31744 non-negative finite codes"
    (List.range 0 (inf_code - 1))
    ~min:(inf_code - 1)
    ~f:(fun c -> Float.( < ) (reference_decode c) (reference_decode (c + 1)));
  (* Counted rather than folded into the claim: the gate decides whether the count is read, and
     without [_Float16] there is nothing to call. *)
  let native_widen_disagreements =
    if not native then 0
    else
      List.count codes ~f:(fun c ->
          let n = native_widen c in
          not (if is_nan_code c then Float.is_nan n else same n widened.(c)))
  in
  if native_widen_disagreements > 0 then
    Stdio.eprintf "widening: %d native disagreements (not part of the golden)\n"
      native_widen_disagreements;
  Verdict.gated ~aggregation:`Environment ~when_:native ~on
    "half_to_float_emulated agrees with the native _Float16 widening on all 65536 codes, NaNs up \
     to sign and payload"
    (native_widen_disagreements = 0);
  Verdict.p_all
    "every non-NaN code survives a widen-and-narrow round trip through the emulated pair" codes
    ~min:0x10000 ~f:(fun c -> is_nan_code c || emulated_narrow widened.(c) = c);
  Verdict.p_all "every NaN code widens to a NaN that narrows back to the quiet NaN 0x7E00" codes
    ~min:0x10000 ~f:(fun c ->
      (not (is_nan_code c)) || emulated_narrow widened.(c) land 0x7FFF = qnan_code);

  (* The C entry points' argument guards, exercised: a guard that has never fired is a claim about
     nothing. *)
  let refuses f =
    try
      f ();
      false
    with Invalid_argument _ -> true
  in
  let one_word : sweep_buf =
    Stdlib.Bigarray.Array1.create Stdlib.Bigarray.int64 Stdlib.Bigarray.c_layout 1
  in
  Verdict.p "the reference decode refuses a code that is not a finite half magnitude"
    (refuses (fun () -> ignore (reference_decode inf_code : float))
    && refuses (fun () -> ignore (reference_decode (-1) : float)));
  Verdict.p "the widening entry points refuse a code outside 16 bits"
    (refuses (fun () -> ignore (emulated_widen 0x10000 : float))
    && refuses (fun () -> ignore (emulated_widen (-1) : float)));
  Verdict.p "the sweep refuses a counters buffer too short to hold its results"
    (refuses (fun () -> sweep_narrow 0L 1L one_word));
  Verdict.p "the sweep refuses a negative base or count"
    (refuses (fun () -> sweep_narrow (-1L) 1L (fresh_buf ()))
    && refuses (fun () -> sweep_narrow 0L (-1L) (fresh_buf ())));

  (* The format's landmarks, as hex floats so the golden is platform-independent. *)
  Stdio.printf "  smallest subnormal (0x0001): %s\n" (Test_utils.hex_float widened.(0x0001));
  Stdio.printf "  largest subnormal (0x03FF): %s\n" (Test_utils.hex_float widened.(0x03FF));
  Stdio.printf "  smallest normal (0x0400): %s\n" (Test_utils.hex_float widened.(0x0400));
  Stdio.printf "  largest finite (0x7BFF): %s\n" (Test_utils.hex_float widened.(0x7BFF));
  Stdio.printf "  negative zero (0x8000): %s\n" (Test_utils.hex_float widened.(0x8000))
