name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          # Error: Package 'darcs' has no installation candidate
          # - ubuntu-latest
          - ubuntu-22.04
          - macos-latest
          # Native support for OCaml not verified yet.
          # - windows-latest
          # Either the waiting queue for FreeBSD is very long, or it is not available.
          # - freebsd-latest
        ocaml-compiler:
          - 5.2.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam depext -yt ocannl_npy arrayjit neural_nets_lib
    - run: opam install . --deps-only --with-test --with-doc
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
