name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
          # Either the waiting queue for FreeBSD is very long, or it is not available.
          # - freebsd-latest
        ocaml-compiler:
          - 5.3.x
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set git to use LF
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global core.ignorecase false
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
        allow-prerelease-opam: true
    # FIXME: We need to pin printbox-text until > 0.12.0 is released.
    - run: opam pin -n printbox-text https://github.com/c-cube/printbox.git
    - run: opam pin -n .
    - run: opam install . -y --deps-only --with-test --with-doc
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
