name: github pages docs

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
    paths:
      - "docs/**"
      - ".github/workflows/gh-pages-docs.yml"

jobs:
  deploy:
    # Avoid Ubuntu 24.04, see: https://github.com/ocaml/opam/issues/5968
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@main

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: opam-ubuntu-22.04-5.3.0

      - name: slipshow
        run: opam install slipshow

      - name: Introductory slides
        run: opam exec -- slipshow compile docs/slides-basics_backprop_training_codegen.md -o docs/html/basics_backprop_training_codegen.html

      - name: RL slides
        run: opam exec -- slipshow compile docs/slides-RL-REINFORCE.md -o docs/html/RL-REINFORCE.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
          destination_dir: docs
          enable_jekyll: true
